const quotes = [
  { text: '人生最大的荣耀不在于从不跌倒，而在于每次跌倒后都能爬起来。', author: '纳尔逊·曼德拉' },
  { text: '想象力比知识更重要。', author: '阿尔伯特·爱因斯坦' },
  { text: '成为你希望在世界上看到的那种改变。', author: '圣雄甘地' },
  { text: '生活不是等待暴风雨过去，而是学会在雨中起舞。', author: '维维安·格林' },
  { text: '成功就是从失败到失败，却依然不失去热情。', author: '温斯顿·丘吉尔' },
  { text: '最好的预言过去是现在，最好的未来从今天开始。', author: '彼得·德鲁克' },
  { text: '行动不一定带来快乐，但没有行动决不可能有快乐。', author: '本杰明·迪斯雷利' },
  { text: '勇气并非没有恐惧，而是判断有些事比恐惧更重要。', author: '安布罗斯·雷德蒙' },
  { text: '预测未来最好的方法就是创造它。', author: '亚伯拉罕·林肯' },
  { text: '不要问世界需要什么，问什么让你充满活力，然后去做。', author: '霍华德·瑟曼' },
  { text: '努力不一定会成功，但放弃一定会失败。', author: '科比·布莱恩特' },
  { text: '种一棵树最好的时间是十年前，其次是现在。', author: '中国谚语' },
  { text: '唯一不可能的事，是你认为不可能的事。', author: '奥黛丽·赫本' },
  { text: '我们看待问题的方式就是问题本身。', author: '阿尔伯特·爱因斯坦' },
  { text: '并非因为事情太难我们不敢做，而是因为我们不敢做事情才难。', author: '塞内卡' },
  { text: '路虽远，行则将至。事虽难，做则必成。', author: '荀子' },
  { text: '如果你每天都在做自己擅长的事情，那么你的能力永远不会超出这个范围。', author: '乔布斯' },
  { text: '人生就像一盒巧克力，你永远不知道下一颗是什么味道。', author: '《阿甘正传》' },
  { text: '失败是成功之母，但别忘了成功也可能是失败之父。', author: '沃伦·巴菲特' },
  { text: '不要用战术上的勤奋，掩盖战略上的懒惰。', author: '雷军' },
  { text: '坚持做正确的事，比把事情做正确更重要。', author: '彼得·德鲁克' },
  { text: '每个人的时间都是有限的，不要浪费时间活在别人的生活里。', author: '乔布斯' },
  { text: 'Stay hungry, stay foolish.', author: '乔布斯' },
  { text: '生活就像骑自行车，要想保持平衡就得往前走。', author: '阿尔伯特·爱因斯坦' },
  { text: '一切伟大的行动和思想，都有一个微不足道的开始。', author: '阿尔贝·加缪' },
  { text: '过去可以借鉴，未来可以规划，但只有当下才是你真正拥有的。', author: '佛陀' },
  { text: '今天很残酷，明天更残酷，后天很美好，但大多数人死在明天晚上。', author: '马云' },
  { text: '不积跬步，无以至千里；不积小流，无以成江海。', author: '荀子' },
  { text: '学习不是填满一桶水，而是点燃一团火。', author: '威廉·巴特勒·叶芝' },
  { text: '你无法教会一个人任何东西，你只能帮助他自己去发现。', author: '伽利略' },
  { text: '知识就是力量，但更重要的是运用知识的智慧。', author: '弗朗西斯·培根' },
  { text: '一个人知道自己为什么而活，就可以忍受任何一种生活。', author: '尼采' },
  { text: '人生最大的冒险，就是过你梦想的生活。', author: '奥普拉·温弗瑞' },
  { text: '决定我们成为什么样人的，不是我们的能力，而是我们的选择。', author: 'J.K. 罗琳' },
  { text: '要么你掌控命运，要么命运掌控你。', author: '吉姆·罗恩' },
  { text: '不要等待机会，而要创造机会。', author: '乔治·伯纳德·肖' },
  { text: '你花时间最多的事情，就是你人生中最重要的事情。', author: '纳瓦尔·拉维康特' },
  { text: '人生最大的遗憾不是失败，而是我本可以。', author: '佚名' },
  { text: '一个人几乎可以在任何他怀有无限热忱的事情上成功。', author: '查尔斯·施瓦布' },
  { text: '成功的秘诀在于：当机会来临时，你已经准备好了。', author: '本杰明·迪斯雷利' },
  { text: '真正的发现之旅不在于寻找新风景，而在于拥有新的眼睛。', author: '马塞尔·普鲁斯特' },
  { text: '不要因为走了太远，而忘了为什么出发。', author: '纪伯伦' },
  { text: '活着就是为了改变世界，难道还有其他原因吗？', author: '乔布斯' },
  { text: '你可以从别人那里得来思想，但你的思考方式必须是你自己的。', author: '叔本华' },
  { text: '学而不思则罔，思而不学则殆。', author: '孔子' },
  { text: '知之者不如好之者，好之者不如乐之者。', author: '孔子' },
  { text: '三军可夺帅也，匹夫不可夺志也。', author: '孔子' },
  { text: '天行健，君子以自强不息。', author: '《周易》' },
  { text: '千里之行，始于足下。', author: '老子' },
  { text: '知人者智，自知者明。胜人者有力，自胜者强。', author: '老子' },
  { text: '为学日益，为道日损。', author: '老子' },
  { text: '人生如逆旅，我亦是行人。', author: '苏轼' },
  { text: '古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。', author: '苏轼' },
  { text: '纸上得来终觉浅，绝知此事要躬行。', author: '陆游' },
  { text: '山重水复疑无路，柳暗花明又一村。', author: '陆游' },
  { text: '宝剑锋从磨砺出，梅花香自苦寒来。', author: '佚名·警世贤文' },
  { text: '书山有路勤为径，学海无涯苦作舟。', author: '韩愈' },
  { text: '业精于勤，荒于嬉；行成于思，毁于随。', author: '韩愈' },
  { text: '读书破万卷，下笔如有神。', author: '杜甫' },
  { text: '会当凌绝顶，一览众山小。', author: '杜甫' },
  { text: '长风破浪会有时，直挂云帆济沧海。', author: '李白' },
  { text: '天生我材必有用，千金散尽还复来。', author: '李白' },
  { text: '苟日新，日日新，又日新。', author: '《大学》' },
  { text: '博学之，审问之，慎思之，明辨之，笃行之。', author: '《中庸》' },
  { text: '不飞则已，一飞冲天；不鸣则已，一鸣惊人。', author: '司马迁' },
  { text: '天下事有难易乎？为之，则难者亦易矣；不为，则易者亦难矣。', author: '彭端淑' },
  { text: '人生能有几回搏，此时不搏何时搏。', author: '容国团' },
  { text: '世界上只有一种真正的英雄主义，那就是认清生活的真相后依然热爱生活。', author: '罗曼·罗兰' },
  { text: '你的时间有限，所以不要为别人而活。', author: '乔布斯' },
  { text: '在信息的汪洋中，独立思考是唯一的救生衣。', author: '卡尔·萨根' },
  { text: '质胜文则野，文胜质则史。文质彬彬，然后君子。', author: '孔子' },
  { text: '君子坦荡荡，小人长戚戚。', author: '孔子' },
  { text: '己所不欲，勿施于人。', author: '孔子' },
  { text: '世上本没有路，走的人多了，也便成了路。', author: '鲁迅' },
  { text: '哪里有天才，我是把别人喝咖啡的工夫都用在工作上的。', author: '鲁迅' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'What we think, we become.', author: 'Buddha' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'I think, therefore I am.', author: 'René Descartes' },
  {
    text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.',
    author: 'Ralph Waldo Emerson',
  },
  { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates' },
  {
    text: 'It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.',
    author: 'Seneca',
  },
  { text: "Code is like humor. When you have to explain it, it's bad.", author: 'Cory House' },
  { text: 'First, solve the problem. Then, write the code.', author: 'John Johnson' },
  { text: 'Talk is cheap. Show me the code.', author: 'Linus Torvalds' },
  { text: 'The best error message is the one that never shows up.', author: 'Thomas Fuchs' },
  {
    text: 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.',
    author: 'Martin Fowler',
  },
  { text: 'Premature optimization is the root of all evil.', author: 'Donald Knuth' },
  { text: '世界上有两种东西是无限的，宇宙和人类的愚蠢，而我对前者还不确定。', author: '阿尔伯特·爱因斯坦' },
  { text: '聪明是一种天赋，而善良是一种选择。', author: '杰夫·贝索斯' },
  { text: '人生最重要的不是所站的位置，而是所朝的方向。', author: '奥利弗·温德尔·霍姆斯' },
  { text: '思维决定行为，行为决定习惯，习惯决定性格，性格决定命运。', author: '杰克·坎菲尔德' },
  { text: '不要停止奔跑，不要回顾来路，来路无可眷恋，值得期待的只有前方。', author: '《马男波杰克》' },
];

function getDayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

export function getDailyQuote(): string {
  const dayOfYear = getDayOfYear(new Date());
  const index = (dayOfYear - 1) % quotes.length;
  const quote = quotes[index];
  return `${quote.text} —— ${quote.author}`;
}
